### 业务方配置
### 列表
http://192.168.25.142:8081/businessconfig/list

### 新增
POST http://192.168.25.142:8081/businessconfig/add
content-type: application/json

{
    "companyName":"工具测试",
    "companyDesc":"工具测试描述"
}

### 修改
